let nome = prompt("qual seu nome?")
let sobrenome = prompt("e qual seu sobrenome?")
alert("seu nome completo é " + nome  + ' ' + sobrenome)
console.log(nome.toUpperCase())
console.log(nome.toLowerCase())
console.log(sobrenome.toUpperCase())
console.log(sobrenome.toLowerCase())
console.log(nome.length())
console.log(sobrenome.length())